name: Lint, Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Prepare
        run: make prepare
      - name: Lint
        run: make lint
      - name: Build
        run: make build-gh-pages
        env:
          USERNAME: franzdiebold
          REPOSITORY_NAME: ng2d-quiz-app
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.2.2
        with:
          branch: gh-pages
          folder: quiz-app/src/dist/quiz-app
